apiVersion: operator.openshift.io/v1
kind: DNS
metadata:
  name: default
spec:
  upstreamResolvers:
    policy: Sequential
    upstreams:
    - type: Network
      address: 10.78.214.40
      port: 53
